apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.replicas.api }}
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      serviceAccountName: {{ .Values.serviceAccount }}
      containers:
        - name: api
          image: "{{ .Values.image.repository }}/devplatform-api:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.api.port }}
          envFrom:
            - secretRef:
                name: {{ .Values.dbSecret }}
          env:
            - name: REDIS_ADDR
              value: {{ .Values.api.env.REDIS_ADDR }}
            - name: BASE_DOMAIN
              value: {{ .Values.api.env.BASE_DOMAIN }}
            - name: REGISTRY
              value: {{ .Values.api.env.REGISTRY }}
            - name: GITHUB_TOKEN
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.gitSecret }}
                  key: GITHUB_TOKEN
            - name: PORT
              value: "{{ .Values.api.port }}"
          resources:
            {{- toYaml .Values.api.resources | nindent 12 }}
