apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.replicas.web }}
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
        - name: web
          image: "{{ .Values.image.repository }}/devplatform-web:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.web.port }}
          resources:
            {{- toYaml .Values.web.resources | nindent 12 }}
